spring:
  application:
    name: config-server
  #profiles:
    #active: native
  cloud:
    config:
      server:
        #native:
          #searchLocations: file:///C:\Users\JOAQUIN\Documents\SpringBoot_projects\config-server-data
        git:
          uri: https://github.com/jhadevback/config-server-data.git
          clone-on-start: true
          default-label: dev
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
          skip-ssl-validation: true
          timeout: 5

server:
  port: 8888
